version: '2'
services:
    atletamedalla-app:
        image: atletamedalla
        external_links:
            - atletamedalla-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/atletamedalla?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    atletamedalla-mysql:
        extends:
            file: mysql.yml
            service: atletamedalla-mysql
